"""empty message

Revision ID: 105d18961bbf
Revises: 3f0c29daab07
Create Date: 2015-08-18 13:05:44.400967

"""

# revision identifiers, used by Alembic.
revision = '105d18961bbf'
down_revision = '3f0c29daab07'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dy_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('expired', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dy_code_code'), 'dy_code', ['code'], unique=False)
    op.create_index(op.f('ix_dy_code_email'), 'dy_code', ['email'], unique=False)
    op.create_index(op.f('ix_dy_code_mobile'), 'dy_code', ['mobile'], unique=False)
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('operation', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('operation')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('mobile', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_mobile'), 'user', ['mobile'], unique=True)
    op.create_table('association',
    sa.Column('left_id', sa.Integer(), nullable=True),
    sa.Column('right_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_id'], [u'role.id'], ),
    sa.ForeignKeyConstraint(['right_id'], [u'permission.id'], )
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('address_province', sa.String(length=32), nullable=True),
    sa.Column('address_city', sa.String(length=32), nullable=True),
    sa.Column('address_district', sa.String(length=32), nullable=True),
    sa.Column('address_detail', sa.String(length=64), nullable=True),
    sa.Column('admin', sa.Integer(), nullable=True),
    sa.Column('certified', sa.Boolean(), nullable=True),
    sa.Column('license1', sa.String(length=256), nullable=True),
    sa.Column('license2', sa.String(length=256), nullable=True),
    sa.Column('license3', sa.String(length=256), nullable=True),
    sa.Column('license4', sa.String(length=256), nullable=True),
    sa.Column('license5', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['admin'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=True)
    op.create_table('user_access_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('last_ip', sa.String(length=16), nullable=True),
    sa.Column('last_device', sa.String(length=128), nullable=True),
    sa.Column('last_position_x', sa.Float(), nullable=True),
    sa.Column('last_position_y', sa.Float(), nullable=True),
    sa.Column('date_expired', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_access_token_token'), 'user_access_token', ['token'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_access_token_token'), table_name='user_access_token')
    op.drop_table('user_access_token')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_table('company')
    op.drop_table('association')
    op.drop_index(op.f('ix_user_mobile'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('permission')
    op.drop_index(op.f('ix_dy_code_mobile'), table_name='dy_code')
    op.drop_index(op.f('ix_dy_code_email'), table_name='dy_code')
    op.drop_index(op.f('ix_dy_code_code'), table_name='dy_code')
    op.drop_table('dy_code')
    ### end Alembic commands ###
