"""empty message

Revision ID: 10c20ece5694
Revises: 43bbae23cbf5
Create Date: 2015-08-19 14:33:13.291858

"""

# revision identifiers, used by Alembic.
revision = '10c20ece5694'
down_revision = '43bbae23cbf5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('license1_id', sa.Integer(), nullable=True))
    op.add_column('company', sa.Column('license2_id', sa.Integer(), nullable=True))
    op.add_column('company', sa.Column('license3_id', sa.Integer(), nullable=True))
    op.add_column('company', sa.Column('license4_id', sa.Integer(), nullable=True))
    op.add_column('company', sa.Column('license5_id', sa.Integer(), nullable=True))
    op.add_column('company', sa.Column('status', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_company_status'), 'company', ['status'], unique=False)
    op.drop_constraint(u'company_license1_fkey', 'company', type_='foreignkey')
    op.drop_constraint(u'company_license3_fkey', 'company', type_='foreignkey')
    op.drop_constraint(u'company_license2_fkey', 'company', type_='foreignkey')
    op.drop_constraint(u'company_license5_fkey', 'company', type_='foreignkey')
    op.drop_constraint(u'company_license4_fkey', 'company', type_='foreignkey')
    op.create_foreign_key(None, 'company', 'attachment', ['license5_id'], ['id'])
    op.create_foreign_key(None, 'company', 'attachment', ['license4_id'], ['id'])
    op.create_foreign_key(None, 'company', 'attachment', ['license3_id'], ['id'])
    op.create_foreign_key(None, 'company', 'attachment', ['license2_id'], ['id'])
    op.create_foreign_key(None, 'company', 'attachment', ['license1_id'], ['id'])
    op.drop_column('company', 'license3')
    op.drop_column('company', 'license2')
    op.drop_column('company', 'license1')
    op.drop_column('company', 'license5')
    op.drop_column('company', 'license4')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('license4', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('license5', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('license1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('license2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('license3', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.create_foreign_key(u'company_license4_fkey', 'company', 'attachment', ['license4'], ['id'])
    op.create_foreign_key(u'company_license5_fkey', 'company', 'attachment', ['license5'], ['id'])
    op.create_foreign_key(u'company_license2_fkey', 'company', 'attachment', ['license2'], ['id'])
    op.create_foreign_key(u'company_license3_fkey', 'company', 'attachment', ['license3'], ['id'])
    op.create_foreign_key(u'company_license1_fkey', 'company', 'attachment', ['license1'], ['id'])
    op.drop_index(op.f('ix_company_status'), table_name='company')
    op.drop_column('company', 'status')
    op.drop_column('company', 'license5_id')
    op.drop_column('company', 'license4_id')
    op.drop_column('company', 'license3_id')
    op.drop_column('company', 'license2_id')
    op.drop_column('company', 'license1_id')
    ### end Alembic commands ###
