"""empty message

Revision ID: 11c4563928ef
Revises: 105d18961bbf
Create Date: 2015-08-18 13:43:10.648964

"""

# revision identifiers, used by Alembic.
revision = '11c4563928ef'
down_revision = '105d18961bbf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    ### end Alembic commands ###
