"""empty message

Revision ID: 3f0c29daab07
Revises: 4cfd9359da11
Create Date: 2015-08-10 13:04:26.179501

"""

# revision identifiers, used by Alembic.
revision = '3f0c29daab07'
down_revision = '4cfd9359da11'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_access_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('last_ip', sa.String(length=16), nullable=True),
    sa.Column('last_device', sa.String(length=128), nullable=True),
    sa.Column('last_position_x', sa.Float(), nullable=True),
    sa.Column('last_position_y', sa.Float(), nullable=True),
    sa.Column('date_expired', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], [u'account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_access_token_token'), 'account_access_token', ['token'], unique=False)
    op.add_column(u'account', sa.Column('password', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'account', ['password'])
    op.add_column(u'dynamic_valid_code', sa.Column('expired', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'dynamic_valid_code', 'expired')
    op.drop_constraint(None, 'account', type_='unique')
    op.drop_column(u'account', 'password')
    op.drop_index(op.f('ix_account_access_token_token'), table_name='account_access_token')
    op.drop_table('account_access_token')
    ### end Alembic commands ###
