"""empty message

Revision ID: 43bbae23cbf5
Revises: 41986eccd7ef
Create Date: 2015-08-19 13:50:35.676494

"""

# revision identifiers, used by Alembic.
revision = '43bbae23cbf5'
down_revision = '41986eccd7ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('key', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('mimetype', sa.String(length=64), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_expired', sa.DateTime(), nullable=True),
    sa.Column('server', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grant_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('res_model', sa.String(length=32), nullable=True),
    sa.Column('res_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], [u'permission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grant_permission_res_id'), 'grant_permission', ['res_id'], unique=False)
    op.create_index(op.f('ix_grant_permission_res_model'), 'grant_permission', ['res_model'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('mobile', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_email'), 'staff', ['email'], unique=True)
    op.create_index(op.f('ix_staff_mobile'), 'staff', ['mobile'], unique=True)
    op.add_column(u'company', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'company_admin_fkey', 'company', type_='foreignkey')
    op.create_foreign_key(None, 'company', 'user', ['admin_id'], ['id'])
    op.drop_column(u'company', 'license1')
    op.drop_column(u'company', 'license2')
    op.drop_column(u'company', 'license3')
    op.drop_column(u'company', 'license4')
    op.drop_column(u'company', 'license5')
    op.add_column(u'company', sa.Column('license1', sa.Integer, nullable=True))
    op.add_column(u'company', sa.Column('license2', sa.Integer, nullable=True))
    op.add_column(u'company', sa.Column('license3', sa.Integer, nullable=True))
    op.add_column(u'company', sa.Column('license4', sa.Integer, nullable=True))
    op.add_column(u'company', sa.Column('license5', sa.Integer, nullable=True))
    op.create_foreign_key(None, 'company', 'attachment', ['license1'], ['id'])
    op.create_foreign_key(None, 'company', 'attachment', ['license2'], ['id'])
    op.create_foreign_key(None, 'company', 'attachment', ['license3'], ['id'])
    op.create_foreign_key(None, 'company', 'attachment', ['license4'], ['id'])
    op.create_foreign_key(None, 'company', 'attachment', ['license5'], ['id'])
    op.drop_column(u'company', 'admin')
    op.add_column(u'user', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'company', ['company_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column(u'user', 'company_id')
    op.add_column(u'company', sa.Column('admin', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.create_foreign_key(u'company_admin_fkey', 'company', 'user', ['admin'], ['id'])
    op.drop_column(u'company', 'admin_id')
    op.drop_index(op.f('ix_staff_mobile'), table_name='staff')
    op.drop_index(op.f('ix_staff_email'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_grant_permission_res_model'), table_name='grant_permission')
    op.drop_index(op.f('ix_grant_permission_res_id'), table_name='grant_permission')
    op.drop_table('grant_permission')
    op.drop_table('attachment')
    ### end Alembic commands ###
