"""empty message

Revision ID: 4cfd9359da11
Revises: None
Create Date: 2015-08-08 17:09:26.320276

"""

# revision identifiers, used by Alembic.
revision = '4cfd9359da11'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('mobile', sa.String(length=16), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('nickname', sa.String(length=80), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('username')
    )
    op.create_table('dynamic_valid_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dynamic_valid_code_code'), 'dynamic_valid_code', ['code'], unique=False)
    op.create_index(op.f('ix_dynamic_valid_code_email'), 'dynamic_valid_code', ['email'], unique=False)
    op.create_index(op.f('ix_dynamic_valid_code_mobile'), 'dynamic_valid_code', ['mobile'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dynamic_valid_code_mobile'), table_name='dynamic_valid_code')
    op.drop_index(op.f('ix_dynamic_valid_code_email'), table_name='dynamic_valid_code')
    op.drop_index(op.f('ix_dynamic_valid_code_code'), table_name='dynamic_valid_code')
    op.drop_table('dynamic_valid_code')
    op.drop_table('account')
    ### end Alembic commands ###
